tenants:
  tenant1:
    workspace1: "<TOKEN_FOR_WORKSPACE1>"
    workspace2: "<TOKEN_FOR_WORKSPACE2>"
  tenant2:
    workspace1: "<TOKEN_FOR_WORKSPACE1>"
  tenant3:
    workspace1: "<TOKEN_FOR_WORKSPACE1>"
    workspace2: "<TOKEN_FOR_WORKSPACE2>"